# -*- coding: utf-8 -*-
"""Banco de preguntas del examen final (Parte A): 40 preguntas de las sesiones 01 a 15,
en tres bloques. El Aula Virtual sortea 8 del bloque 1, 7 del bloque 2 y 5 del bloque 3.
Ninguna se repite en el simulacro (cuestionario-sesion16.html).
"""


def q(sesion, tema, p, o, c, e):
    assert len(o) == 4 and 0 <= c < 4
    return {'sesion': sesion, 'tema': tema, 'p': p, 'o': o, 'c': c, 'e': e}


BLOQUES = [
    ('Bloque 1 · HTML5 y Figma (sesiones 01 a 07)', 8, [
        q('01', 'Estándares', '¿Qué hace el validador del W3C (validator.w3.org)?',
          ['Revisa que el HTML cumpla el estándar y lista sus errores', 'Publica la página en internet', 'Diseña la página automáticamente', 'Mide la velocidad de la conexión'], 0,
          'Antes de entregar, las páginas deben pasar el validador sin errores.'),
        q('01', 'Lenguajes', '¿Qué papel cumple cada lenguaje en una página web?',
          ['CSS da la estructura, HTML el estilo y JavaScript el contenido', 'HTML da la estructura y el contenido, CSS la presentación y JavaScript el comportamiento', 'Los tres hacen lo mismo', 'JavaScript da la estructura y HTML los colores'], 1,
          'Separar estructura, presentación y comportamiento es la base del curso.'),
        q('02', 'Documento', '¿Para qué sirve `<meta charset="UTF-8">` dentro del `<head>`?',
          ['Para enlazar la hoja de estilos', 'Para que la página cargue más rápido', 'Para que las tildes, la ñ y los signos se muestren bien', 'Para poner el título de la pestaña'], 2,
          'Va al inicio del `<head>`.'),
        q('02', 'Documento', '¿Qué indica `lang="es"` en la etiqueta `<html>`?',
          ['Que la página usa CSS en español', 'Que la página solo se ve en Perú', 'Que el código está traducido', 'El idioma del contenido: el lector de pantalla lo pronuncia en español y los buscadores lo saben'], 3,
          'Lighthouse lo revisa en la categoría SEO.'),
        q('02', 'Listas', '¿Qué diferencia hay entre `<ul>` y `<ol>`?',
          ['`<ul>` es una lista con viñetas y `<ol>`, una lista numerada', '`<ol>` es una lista con viñetas y `<ul>`, una numerada', 'No hay diferencia', '`<ul>` solo sirve para menús'], 0,
          'Los menús de navegación se escriben con `<ul>` dentro de `<nav>`.'),
        q('03', 'Semántica', '¿Qué etiqueta lleva los datos de contacto y los derechos al final de la página?',
          ['`<aside>`', '`<footer>`', '`<bottom>`', '`<section>`'], 1,
          '`<bottom>` no existe en HTML.'),
        q('03', 'Semántica', '¿En qué se diferencia `<section>` de `<div>`?',
          ['`<div>` es más moderno', 'No hay diferencia', '`<section>` agrupa un contenido temático con su título; `<div>` no tiene significado y solo sirve para dar estilos', '`<section>` solo puede ir en el pie'], 2,
          'El lector de pantalla y los buscadores entienden `<section>`; un `<div>` no les dice nada.'),
        q('04', 'Rutas', 'Desde `index.html`, ¿cuál es la ruta relativa a `foto.jpg`, guardada en `assets/img/`?',
          ['`/foto.jpg`', '`C:/assets/img/foto.jpg`', '`../foto.jpg`', '`assets/img/foto.jpg`'], 3,
          'Una ruta relativa parte de la carpeta del archivo HTML.'),
        q('04', 'Enlaces', '¿Qué hace `<a href="mailto:docente@uss.edu.pe">`?',
          ['Abre el programa de correo con un mensaje nuevo para esa dirección', 'Envía el formulario a esa dirección', 'Valida el correo', 'Abre la página de la universidad'], 0,
          'Con `tel:` se abre la llamada en el celular.'),
        q('04', 'Imágenes', '¿Por qué se escriben `width` y `height` en una `<img>`?',
          ['Para que la imagen pese menos', 'Para que el navegador reserve su espacio y la página no salte al cargar', 'Para que se vea en blanco y negro', 'Porque reemplazan al atributo `alt`'], 1,
          'Con `max-width: 100%` y `height: auto` en el CSS, la imagen sigue siendo adaptable.'),
        q('05', 'Tablas', '¿Qué hace `colspan="2"` en una celda?',
          ['Duplica el texto', 'Separa la celda en dos', 'Hace que la celda ocupe dos columnas', 'Hace que la celda ocupe dos filas'], 2,
          'Para ocupar dos filas se usa `rowspan`.'),
        q('05', 'Tablas', '¿Para qué sirve `<th scope="col">`?',
          ['Para centrar la columna', 'Para pintar la columna', 'Para ocultar la columna', 'Para indicar que esa celda es el encabezado de su columna, y el lector de pantalla lo anuncie'], 3,
          'Con `scope="row"` encabeza su fila.'),
        q('06', 'Formularios', '¿Qué pasa si un `<input>` no tiene el atributo `name`?',
          ['Su dato no se envía con el formulario', 'El campo no se ve', 'El formulario no se puede abrir', 'Nada: `name` es opcional para enviar'], 0,
          'Netlify Forms también guarda solo los campos que tienen `name`.'),
        q('06', 'Formularios', '¿Qué etiquetas agrupan campos relacionados y les dan un título?',
          ['`<div>` y `<h2>`', '`<fieldset>` y `<legend>`', '`<group>` y `<title>`', '`<form>` y `<label>`'], 1,
          'El formulario de contacto del portafolio usa un `fieldset` en cada columna.'),
        q('06', 'Formularios', '¿Con qué etiquetas se escribe una lista desplegable de opciones?',
          ['`<input type="list">`', '`<ul>` y `<li>`', '`<select>` con sus `<option>`', '`<datalist>` sin campo'], 2,
          'La primera opción puede tener `value=""` para obligar a elegir con `required`.'),
        q('07', 'Multimedia', '¿Por qué un `<video>` lleva varias etiquetas `<source>`?',
          ['Para reproducir los videos uno tras otro', 'Para mostrar varios videos a la vez', 'Para agregar subtítulos', 'Para ofrecer varios formatos: el navegador usa el primero que puede reproducir'], 3,
          'Por ejemplo, WebM y MP4.'),
        q('07', 'Multimedia', '¿Qué etiqueta agrega subtítulos a un video?',
          ['`<track kind="subtitles" src="subtitulos.vtt">`', '`<caption>`', '`<source type="text">`', '`<subtitle>`'], 0,
          'El archivo de subtítulos usa el formato WebVTT.'),
        q('07', 'Figma', 'En Figma, ¿qué hace `Shift + A` con una capa seleccionada?',
          ['La duplica', 'Activa la Disposición automática: la envuelve en un marco que ordena su contenido', 'La exporta', 'La convierte en componente'], 1,
          'La Disposición automática de Figma equivale a Flexbox en CSS.'),
    ]),
    ('Bloque 2 · CSS3 y diseño responsivo (sesiones 09 a 12)', 7, [
        q('09', 'Selectores', '¿A qué elementos se aplica el selector `.tarjeta p`?',
          ['Solo al primer párrafo de la página', 'A los elementos que tienen las clases tarjeta y p', 'A todos los párrafos que están dentro de un elemento con la clase tarjeta', 'A las tarjetas que están dentro de un párrafo'], 2,
          'El espacio es el selector descendiente.'),
        q('09', 'Unidades', '¿A qué es relativa la unidad `rem`?',
          ['Al ancho de la ventana', 'Al tamaño de letra del elemento padre', 'Al alto de la pantalla', 'Al tamaño de letra del elemento `html`, 16px por defecto'], 3,
          'Por eso `1.5rem` son 24px si nadie cambió el tamaño de letra del navegador.'),
        q('09', 'Fuentes', '¿Dónde se escribe el `@import` de Google Fonts en una hoja de estilos?',
          ['En la primera línea de la hoja', 'Al final de la hoja', 'Dentro de `:root`', 'En cualquier regla'], 0,
          'Un `@import` después de otras reglas se ignora.'),
        q('10', 'Caja', '¿Qué diferencia hay entre `padding` y `margin`?',
          ['Son lo mismo', '`padding` es el espacio dentro del borde; `margin`, el espacio fuera del borde', '`margin` es el espacio dentro del borde; `padding`, fuera', '`padding` solo funciona en flex'], 1,
          'En Figma, el `padding` es el Espaciado del marco.'),
        q('10', 'Flexbox', 'Un marco de Figma tiene Flujo vertical. ¿Qué se escribe en CSS?',
          ['`flex-wrap: wrap`', '`display: block`', '`display: flex; flex-direction: column`', '`align-items: center`'], 2,
          'El Flujo horizontal es `flex-direction: row`, el valor por defecto.'),
        q('10', 'Flexbox', 'En una fila flex, ¿qué hace `align-items: center`?',
          ['Centra los hijos en horizontal', 'Reparte el espacio entre los hijos', 'Pone los hijos en columna', 'Centra los hijos en el eje vertical, el eje cruzado'], 3,
          'En una fila, `justify-content` trabaja en horizontal y `align-items` en vertical.'),
        q('10', 'Flexbox', '¿Qué propiedad corresponde al Espacio de la Disposición automática de Figma?',
          ['`gap`', '`padding`', '`margin`', '`border-spacing`'], 0,
          '`gap` separa a los hijos sin tocar los bordes del contenedor.'),
        q('11', 'Transformaciones', '¿Qué hace `transform: translateY(-4px)` en el `:hover` de una tarjeta?',
          ['La hace 4px más pequeña', 'La sube 4px sin empujar a los elementos vecinos', 'La gira 4 grados', 'La mueve 4px a la izquierda'], 1,
          'Con `transition`, la subida es suave.'),
        q('11', 'Animaciones', '¿Qué se necesita para que un elemento se anime solo, sin pasar el cursor?',
          ['Solo `transition`', 'Un `:hover`', 'Pasos definidos en `@keyframes` y la propiedad `animation` que los usa', 'JavaScript obligatoriamente'], 2,
          '`transition` necesita un cambio de estado; `animation` se reproduce sola.'),
        q('11', 'Accesibilidad', '¿Para qué sirve `@media (prefers-reduced-motion: reduce)`?',
          ['Para que el sitio cargue más rápido', 'Para animar solo en el celular', 'Para pausar los videos', 'Para quitar o reducir las animaciones a quien lo pidió en su sistema'], 3,
          'Algunas personas sienten mareo con el movimiento en pantalla.'),
        q('12', 'Responsive', '¿Qué significa diseñar «celular primero»?',
          ['Escribir los estilos base para el celular y agregar `min-width` para las pantallas grandes', 'Diseñar solo para el celular', 'Usar solo `max-width`', 'Crear una página aparte para el celular'], 0,
          'Las media queries con `min-width` van de menor a mayor.'),
        q('12', 'Imágenes', '¿Qué hace `img { max-width: 100%; height: auto; }`?',
          ['Agranda todas las imágenes', 'La imagen nunca sale de su contenedor y conserva su proporción', 'Recorta las imágenes', 'Oculta las imágenes en el celular'], 1,
          'Es una de las primeras reglas de un sitio adaptable.'),
        q('12', 'Pruebas', '¿Cómo pruebas tu página a 390 px de ancho sin un celular?',
          ['Achicando la letra', 'Cambiando el CSS a 390px', 'Con las herramientas del navegador (`F12`) y la barra de dispositivos', 'No se puede'], 2,
          '390 px es el ancho del marco móvil de Figma.'),
    ]),
    ('Bloque 3 · Bootstrap y publicación (sesiones 13 a 15)', 5, [
        q('13', 'Grilla', '¿Qué hace la clase `.container` de Bootstrap?',
          ['Pone un fondo gris', 'Crea una fila de columnas', 'Oculta el contenido', 'Crea una caja centrada con un ancho máximo para cada punto de quiebre'], 3,
          '`.container-fluid` ocupa siempre todo el ancho.'),
        q('13', 'Grilla', '¿Dónde deben estar las columnas `col-*`?',
          ['Dentro de un `.row`', 'Dentro de un `<table>`', 'Directamente en el `<body>`', 'Dentro de un `<ul>`'], 0,
          'La fila prepara el espacio y los medianiles de sus columnas.'),
        q('13', 'Grilla', '¿Qué hace la clase `g-4` en un `.row`?',
          ['Pone cuatro columnas', 'Da un medianil (espacio entre columnas) de 1.5rem, 24px', 'Pone un borde de 4px', 'Agranda la letra'], 1,
          'Coincide con el Medianil 24 de la guía de columnas de Figma.'),
        q('14', 'Componentes', '¿Qué hacen las clases `btn btn-primary`?',
          ['Crean un enlace subrayado', 'Ocultan el botón', 'Dan al elemento el estilo de botón con el color primario del tema', 'Envían el formulario'], 2,
          'En tu tema, `--bs-primary` es el cian de Figma.'),
        q('14', 'Acordeón', 'En un acordeón de Bootstrap, ¿qué indica `collapse show`?',
          ['Que la respuesta no se puede cerrar', 'Que la respuesta está oculta', 'Que se abre al pasar el cursor', 'Que esa respuesta aparece abierta al cargar la página'], 3,
          'Sin `show`, la respuesta empieza cerrada.'),
        q('14', 'Navbar', '¿Qué hace `navbar-expand-lg` en una barra de navegación?',
          ['Muestra el menú completo desde 992 px; por debajo, solo el botón de tres rayas', 'Agranda la barra', 'Fija la barra arriba', 'Oculta el menú siempre'], 0,
          '`lg` es el punto de quiebre de 992 px.'),
        q('15', 'Lighthouse', '¿Qué mide Lighthouse?',
          ['Solo la velocidad de internet', 'El rendimiento, la accesibilidad, las buenas prácticas y el SEO de una página', 'Cuántas personas visitan el sitio', 'Si el diseño es igual a Figma'], 1,
          'Se abre con `F12`, en la pestaña Lighthouse.'),
        q('15', 'Metadatos', '¿Para qué sirve `<meta name="description">`?',
          ['Para describir la página al validador', 'Para cambiar el idioma', 'Es el resumen que suelen mostrar los buscadores debajo del título', 'Para mostrar un texto encima de la página'], 2,
          'Cada página lleva la suya, de unos 150 caracteres.'),
        q('15', 'Netlify', 'Al publicar, Netlify muestra «Page not found» en la página de inicio. ¿Cuál es la causa más probable?',
          ['Falta el favicon', 'Hay un error de CSS', 'El sitio es demasiado grande', '`index.html` no está en la raíz de la carpeta que subiste'], 3,
          'Se arrastra la carpeta que tiene `index.html` directamente dentro.'),
    ]),
]

assert sum(len(b[2]) for b in BLOQUES) == 40
