# -*- coding: utf-8 -*-
"""Cuestionarios de las sesiones 13 y 14, con el mismo generador de las sesiones 09 a 12.
uso: python3 quiz_1314.py <repo>
"""
import os
from quiz import q, generar, REPO

S13 = dict(
    n='13', tema='Introducción a Bootstrap y su sistema de grillas',
    pre_p='Mide lo que recuerdan de la sesión 12 (diseño responsivo) antes de empezar con Bootstrap.',
    post_p='Mide lo que aprendieron hoy: qué es Bootstrap, cómo se instala y su grilla de 12 columnas.',
    pre_desc='Saberes previos (Sesión 12: responsive)', post_desc='Evaluación de salida (Sesión 13 y Figma)',
    pre_badge='RESULTADOS PRETEST (SESIÓN 12)', post_badge='RESULTADOS POSTEST (SESIÓN 13 Y FIGMA)',
    pre_corto='Sesión 12',
    pre_lista=['📱 <strong>Viewport y media queries:</strong> max-width, min-width y el orden',
               '🌊 <strong>Medidas fluidas:</strong> clamp(), auto-fit y aspect-ratio',
               '🧩 <strong>Figma móvil:</strong> el marco de 390'],
    post_lista=['🅱️ <strong>Bootstrap (3 preguntas):</strong> framework, CDN y el orden de las hojas',
                '▦ <strong>La grilla (4 preguntas):</strong> row, col-*, puntos de quiebre y medianiles',
                '🧩 <strong>Figma (3 preguntas):</strong> la guía de columnas, el medianil y offset'],
    pre=[
        q('Sesión 12', 'viewport', '¿Para qué sirve `<meta name="viewport" content="width=device-width, initial-scale=1.0">`?',
          ['Para que el celular use su ancho real y no muestre la página en miniatura', 'Para cargar el CSS', 'Para que la página funcione sin internet', 'Para que el sitio aparezca en Google'], 0,
          'Sin ella, el celular finge una pantalla de unos 980 px y ninguna media query de celular se activa.'),
        q('Sesión 12', 'Media queries', '`@media (min-width: 768px) { … }` se aplica cuando la ventana mide…',
          ['Menos de 768 px', '768 px o más', 'Exactamente 768 px', 'Solo al imprimir'], 1,
          '`min-width` es «desde ese ancho»: es el enfoque celular primero. `max-width` es «hasta ese ancho».'),
        q('Sesión 12', 'Orden', '¿Por qué las media queries se escriben al final de la hoja de estilos?',
          ['Porque el validador lo exige', 'Porque así cargan más rápido', 'Porque una media query no suma especificidad: gana por estar escrita después', 'Porque si no, el navegador las ignora'], 2,
          'Con la misma especificidad gana la regla escrita al final. Si la media query va antes, la regla normal la pisa.'),
        q('Sesión 12', 'clamp()', '¿Qué hace `font-size: clamp(2.5rem, 1.5rem + 4vw, 4rem);`?',
          ['Fija el tamaño en 4rem', 'Elige al azar uno de los tres valores', 'Usa 2.5rem solo en el celular', 'Hace crecer la letra con la pantalla, sin bajar de 2.5rem ni pasar de 4rem'], 3,
          'Usa el valor del medio mientras quede entre el mínimo y el máximo.'),
        q('Sesión 12', 'auto-fit', '¿Qué ventaja tiene `repeat(auto-fit, minmax(360px, 1fr))` en una rejilla?',
          ['Decide sola cuántas columnas caben, sin media query', 'Siempre pone tres columnas', 'Solo funciona en el celular', 'Oculta las tarjetas que no caben'], 0,
          'Pone tantas columnas de al menos 360 px como quepan y las estira con `1fr`.'),
        q('Sesión 12', 'aspect-ratio', '¿Por qué el `iframe` de YouTube necesita `aspect-ratio: 16 / 9`?',
          ['Para reproducirse solo', 'Para tener bordes redondeados', 'Porque un iframe no conserva su proporción con `height: auto`, como una imagen', 'Para pasar el validador'], 2,
          'Con `width: 100%`, `height: auto` y `aspect-ratio`, el navegador calcula el alto a partir del ancho.'),
        q('Sesión 12', 'Tablas', 'En el celular, una tabla de tres columnas no cabe. ¿Qué solución usaste?',
          ['Borrar una columna', 'Una caja con `overflow-x: auto` alrededor: la tabla se desplaza dentro de ella', 'Letra de 6 px', 'Girar la tabla 90 grados'], 1,
          'Las columnas de una tabla no se apilan. La caja `.tabla-scroll` se desplaza y la página no se ensancha.'),
        q('Sesión 12', 'Enfoques', 'Tu portafolio se escribió con el enfoque **escritorio primero**. ¿Qué significa?',
          ['Que las reglas normales son las del escritorio y `max-width` corrige hacia abajo', 'Que solo funciona en escritorio', 'Que el celular carga otra página', 'Que no usa media queries'], 0,
          'Tu diseño nació en un marco de 1440. Bootstrap, en cambio, se escribe celular primero.'),
        q('Sesión 12', 'DevTools', '¿Qué atajo de Chrome activa el modo dispositivo de DevTools?',
          ['`Ctrl + D`', '`Ctrl + Shift + M`', '`Ctrl + Alt + K`', '`F5`'], 1,
          'Con el modo dispositivo pruebas tu página a 390, 820 y 1440 px.'),
        q('Figma', 'Marco móvil', 'En el marco móvil de 390, ¿qué cambiaste en las secciones que tenían dos columnas?',
          ['El color de fondo', 'El nombre de la capa', 'El Flujo: de horizontal (→) a vertical (↓)', 'La fuente'], 2,
          'Cada cambio de Flujo del marco móvil es un `flex-direction: column` en una media query.'),
    ],
    post=[
        q('Sesión 13', 'Framework', '¿Qué es un framework de CSS como Bootstrap?',
          ['Un programa para dibujar interfaces', 'Un conjunto de reglas de CSS ya escritas y probadas que usas con clases', 'Un navegador', 'Un servidor para publicar sitios'], 1,
          'Bootstrap trae Reboot, grilla, utilidades y componentes. Tú eliges qué usar poniendo clases en el HTML.'),
        q('Sesión 13', 'Instalación', '¿En qué orden se enlazan las hojas en `cursos.html`?',
          ['Bootstrap primero y después `global.css`, `header.css` y `cursos.css`', '`cursos.css` primero', 'Bootstrap al final', 'El orden no importa'], 0,
          'Con la misma especificidad gana lo último. Si Bootstrap va primero, tus hojas pueden ajustarlo.'),
        q('Sesión 13', 'integrity', '¿Para qué sirve el atributo `integrity` en el enlace de Bootstrap desde el CDN?',
          ['Para cargarlo más rápido', 'Para que funcione sin internet', 'Para comprobar que el archivo no fue alterado: si no coincide, el navegador no lo usa', 'Para comprimir el archivo'], 2,
          'Es la huella del archivo. Va junto a `crossorigin="anonymous"`.'),
        q('Sesión 13', 'La grilla', '¿Cuál es el orden correcto de las piezas de la grilla?',
          ['`col` › `row` › `container`', '`row` › `container` › `col`', '`container` › `col` › `row`', '`container` › `row` › `col-*`'], 3,
          'El contenedor limita el ancho, la fila reparte 12 columnas y cada `col-*` dice cuántas ocupa.'),
        q('Sesión 13', 'Puntos de quiebre', '¿Cómo se lee `class="col-12 col-md-6 col-lg-4"`?',
          ['Una columna en el celular, dos desde 768 px y tres desde 992 px', 'Siempre tres columnas', 'Tres columnas en el celular y una en escritorio', 'Doce columnas en el celular'], 0,
          'Bootstrap es celular primero: cada clase vale desde su punto de quiebre hacia arriba.'),
        q('Sesión 13', 'Medianiles', '¿Cuánto mide el medianil de `g-4` y dónde se escribe?',
          ['4 px, en cada columna', '24 px, en la `row`', '40 px, en el contenedor', '4 rem, en el body'], 1,
          '`g-4` es 1.5rem: 24 px, como el Medianil de tu guía de Figma. Va en la fila.'),
        q('Sesión 13', 'Reboot', 'Al enlazar Bootstrap, el nombre y el menú de la cabecera se descuadraron. ¿Por qué?',
          ['Bootstrap borra tu CSS', 'Falta la etiqueta viewport', 'El Reboot de Bootstrap da margen al h1 y sangría a las listas con selectores de etiqueta, que le ganan a tu `*`', 'La cabecera no tiene clase'], 2,
          '`header h1` (0-0-2) le gana a `h1` (0-0-1) del Reboot. Por eso el bloque 6 de `header.css` lo resuelve.'),
        q('Figma', 'Guía de columnas', 'En la guía de 12 columnas de `mi-portafolio`, ¿qué valores usaste?',
          ['4 columnas, Margen 16, Medianil 16', '12 columnas, Margen 80, Medianil 24', '10 columnas, Margen 0, Medianil 10', '6 columnas, Margen 40, Medianil 32'], 1,
          'Margen 80 son los márgenes de tu diseño y Medianil 24 es `g-4`.'),
        q('Figma', 'Columnas', 'Con la guía visible, una `course-card` ocupa 4 de las 12 columnas. ¿Qué clase es en Bootstrap?',
          ['`col-4` sin punto de quiebre', '`col-12`', '`g-4`', '`col-lg-4`: tres tarjetas por fila desde 992 px'], 3,
          'Cuentas columnas en Figma y escribes ese número en la clase `col-*`.'),
        q('Figma', 'offset', 'El llamado ocupa 8 columnas y deja 2 vacías a cada lado. ¿Qué clases lo logran?',
          ['`col-lg-8 offset-lg-2`', '`col-lg-10`', '`col-lg-8 order-2`', '`row-cols-8`'], 0,
          '`offset-lg-2` deja 2 columnas vacías a la izquierda: 2 + 8 + 2 = 12.'),
    ],
)

S14 = dict(
    n='14', tema='Bootstrap: componentes, utilidades y tema',
    pre_p='Mide lo que recuerdan de la sesión 13 (la grilla de Bootstrap) antes de usar sus componentes.',
    post_p='Mide lo que aprendieron hoy: utilidades, componentes, el JavaScript de Bootstrap, el tema y las variables de Figma.',
    pre_desc='Saberes previos (Sesión 13: la grilla)', post_desc='Evaluación de salida (Sesión 14 y Figma)',
    pre_badge='RESULTADOS PRETEST (SESIÓN 13)', post_badge='RESULTADOS POSTEST (SESIÓN 14 Y FIGMA)',
    pre_corto='Sesión 13',
    pre_lista=['🅱️ <strong>Bootstrap:</strong> CDN, orden y Reboot',
               '▦ <strong>La grilla:</strong> container, row, col-*, g-4, offset y row-cols',
               '🧩 <strong>Figma:</strong> la guía de columnas'],
    post_lista=['🧱 <strong>Utilidades (3 preguntas):</strong> espaciado, responsivas e !important',
                '🗂️ <strong>Componentes y JavaScript (4 preguntas):</strong> card, acordeón, modal y data-bs-*',
                '🎨 <strong>Tema y Figma (3 preguntas):</strong> --bs-primary, variables locales y variantes'],
    pre=[
        q('Sesión 13', 'Bootstrap', '¿Qué trae Bootstrap además de la grilla?',
          ['Solo colores', 'Un editor de código', 'Reboot, utilidades, componentes y JavaScript para algunos de ellos', 'Un servidor para publicar'], 2,
          'Y aparte, Bootstrap Icons. En la sesión 14 usas las utilidades, los componentes y el JavaScript.'),
        q('Sesión 13', 'CDN', '¿Qué es un CDN?',
          ['Un servidor que entrega archivos públicos muy rápido, que enlazas sin descargarlos', 'Un tipo de selector', 'Un validador', 'Una versión de HTML'], 0,
          'Bootstrap se enlaza desde cdn.jsdelivr.net con `integrity` y `crossorigin`.'),
        q('Sesión 13', 'Columnas', '¿Cuántas columnas tiene una fila de Bootstrap?',
          ['6', '10', '16', '12'], 3,
          'Por eso `col-lg-4` son tres por fila y `col-lg-6`, dos.'),
        q('Sesión 13', 'Columnas', 'En una fila escribes `col-8` y `col-6`. ¿Qué pasa?',
          ['Se encogen para caber', 'La segunda baja a otra línea: suman 14', 'Bootstrap da un error', 'Se superponen'], 1,
          'Las columnas de una fila suman 12 como máximo; lo que sobra baja de línea.'),
        q('Sesión 13', 'Columnas', '¿Qué hace `row-cols-3` en una fila?',
          ['Cada `.col` hija mide un tercio, sin escribir el número en cada una', 'Crea tres filas', 'Deja tres columnas vacías', 'Pone 3 px entre columnas'], 0,
          'Lo usaste en la fila anidada de las cifras.'),
        q('Sesión 13', 'Contenedor', '¿Qué diferencia hay entre `.container` y `.container-fluid`?',
          ['Ninguna', '`.container-fluid` solo funciona en el celular', '`.container` tiene un ancho máximo por punto de quiebre; `.container-fluid` ocupa siempre todo el ancho', '`.container` no se puede usar con `row`'], 2,
          'En tu portafolio, `main` hace de contenedor con los márgenes de 80 de Figma.'),
        q('Sesión 13', 'Puntos de quiebre', '¿Desde qué ancho se aplica `col-lg-4`?',
          ['576 px', '768 px', '1200 px', '992 px'], 3,
          'lg empieza en 992 px: el mismo punto de quiebre de tablet que usaste en la sesión 12.'),
        q('Sesión 13', 'Orden visual', '¿Qué hace `order-lg-1` en una columna?',
          ['La pone primera visualmente desde 992 px, sin cambiar el HTML', 'La borra', 'Le da una columna de ancho', 'La ordena alfabéticamente'], 0,
          'El teclado y el lector de pantalla siguen el orden del HTML: úsalo con cuidado.'),
        q('Sesión 13', 'contenido.css', '¿Por qué la página Cursos no enlaza `contenido.css`?',
          ['Porque está vacía', 'Porque sus reglas de etiqueta (`button`, `article`) chocarían con los componentes de Bootstrap', 'Porque pesa mucho', 'Porque Bootstrap la borra'], 1,
          'En su lugar, `cursos.css` trae solo lo que esa página necesita.'),
        q('Figma', 'Guía de columnas', '¿Qué es el Medianil (Gutter) de la guía de columnas de Figma?',
          ['La distancia entre el borde del marco y la primera columna', 'El color de las columnas', 'La separación entre dos columnas', 'El número de columnas'], 2,
          'El Medianil 24 es la clase `g-4`. La distancia al borde es el Margen.'),
    ],
    post=[
        q('Sesión 14', 'Utilidades', '¿Qué hace la utilidad `mb-3`?',
          ['Un margen inferior de 1rem (16 px)', 'Un relleno de 3 px', 'Un borde de 3 px', 'Una columna de 3'], 0,
          'm es margin, b es bottom (abajo) y 3 es 16 px. Los tamaños van de 0 a 5.'),
        q('Sesión 14', 'Utilidades', '¿Cómo se lee `p-4 p-md-5`?',
          ['Relleno de 4 px y 5 px', 'Relleno de 24 px en el celular y de 48 px desde 768 px', 'Cuatro párrafos', 'Relleno solo en md'], 1,
          'Como la grilla, una utilidad con punto de quiebre vale desde ese ancho hacia arriba.'),
        q('Sesión 14', 'Utilidades', 'Escribiste en tu CSS `.paso { margin-bottom: 2rem; }`, pero el elemento tiene la clase `mb-0` y no cambia. ¿Por qué?',
          ['Porque falta el punto y coma', 'Porque `.paso` no existe', 'Porque Bootstrap está desactualizado', 'Porque las utilidades de Bootstrap usan `!important`'], 3,
          'Las utilidades ganan siempre. Para cambiar el resultado, cambia la clase en el HTML.'),
        q('Sesión 14', 'card', '¿Qué hace `h-100` en las tarjetas `card` del catálogo?',
          ['Les da 100 px de alto', 'Las oculta', 'Les da el alto completo de su columna: las de una fila miden lo mismo', 'Les quita el borde'], 2,
          'Es `height: 100%`. En la sesión 13 lo escribías en `cursos.css`.'),
        q('Sesión 14', 'JavaScript', 'El acordeón no se abre al hacer clic. ¿Qué es lo primero que revisas?',
          ['El color del botón', 'Que el JavaScript de Bootstrap esté enlazado al final del body y que `data-bs-target` apunte al `id` con `#`', 'El tamaño de la letra', 'Que el título sea un h1'], 1,
          'El acordeón y la ventana modal funcionan con `bootstrap.bundle.min.js` y los atributos `data-bs-*`.'),
        q('Sesión 14', 'Acordeón', '¿Qué hace `data-bs-parent="#faq"` en cada respuesta del acordeón?',
          ['Al abrir una, cierra las demás del mismo acordeón', 'Abre todas a la vez', 'Le pone un borde', 'Enlaza el acordeón con el CSS'], 0,
          'Sin él, varias respuestas pueden quedar abiertas a la vez.'),
        q('Sesión 14', 'Modal', '¿Cuál de estas formas **no** cierra la ventana modal de Bootstrap?',
          ['La X con `data-bs-dismiss="modal"`', 'La tecla `Esc`', 'Un clic en el fondo oscuro', 'Pasar el cursor por encima del título'], 3,
          'La ventana se cierra con su botón, con Cancelar, con `Esc` o con un clic fuera de ella.'),
        q('Sesión 14', 'Tema', '¿Qué cambias para que las utilidades `text-primary` y `bg-primary-subtle` usen el cian de Figma?',
          ['Las variables `--bs-primary` y `--bs-primary-rgb` en `:root`', 'La clase en cada elemento', 'El archivo de Bootstrap', 'El HTML de la cabecera'], 0,
          'Bootstrap guarda su tema en variables `--bs-*`. Tu tema va en `tema-bootstrap.css`, justo después de Bootstrap.'),
        q('Figma', 'Variables', 'En Figma, ¿dónde creas la colección `tokens` con tus colores?',
          ['En Capas', 'En la pestaña Prototipo', 'Sin nada seleccionado: Variables locales › Abrir variables', 'En la sección Exportar'], 2,
          'Si cambias una variable, cambian todas las capas que la usan, como en CSS.'),
        q('Figma', 'Variantes', 'La insignia Intermedio es oscura y la Básico, clara. ¿Cómo lo resolviste en Figma?',
          ['Con dos componentes distintos', 'Con el componente `course-card` y las variantes `Nivel=Básico` y `Nivel=Intermedio`', 'Cambiando el color a mano en cada tarjeta', 'Con un prototipo'], 1,
          'Al seleccionar una instancia, la propiedad Nivel cambia la insignia y conserva los textos.'),
    ],
)

if __name__ == '__main__':
    generar(S13, os.path.join(REPO, 'SESION 13', 'cuestionario-sesion13.html'))
    generar(S14, os.path.join(REPO, 'SESION 14', 'cuestionario-sesion14.html'))
