# -*- coding: utf-8 -*-
"""Cuestionarios de las sesiones 15 y 16, con el mismo generador de las sesiones 09 a 14.
La 16 es un simulacro del examen final: la parte 1 repasa HTML5 (sesiones 01 a 07) y la
parte 2, CSS3, Bootstrap y la publicación (sesiones 09 a 15). Sus preguntas no se repiten
en el banco del examen final.
uso: python3 quiz_1516.py <repo>
"""
import os
from quiz import q, generar, REPO

S15 = dict(
    n='15', tema='Proyecto integrador: pruebas y despliegue',
    pre_p='Mide lo que recuerdan de la sesión 14 (componentes y tema de Bootstrap) antes de revisar el sitio completo.',
    post_p='Mide lo que aprendieron hoy: pruebas, el <head> completo, el teclado, la 404, Netlify Forms y la entrega en Figma.',
    pre_desc='Saberes previos (Sesión 14: Bootstrap)', post_desc='Evaluación de salida (Sesión 15 y Figma)',
    pre_badge='RESULTADOS PRETEST (SESIÓN 14)', post_badge='RESULTADOS POSTEST (SESIÓN 15 Y FIGMA)',
    pre_corto='Sesión 14',
    pre_lista=['🧱 <strong>Utilidades:</strong> espaciado, responsivas y visually-hidden',
               '🗂️ <strong>Componentes:</strong> card, modal y el JavaScript de Bootstrap',
               '🎨 <strong>Tema y Figma:</strong> --bs-*, variables locales'],
    post_lista=['🧪 <strong>Pruebas y <head> (3 preguntas):</strong> nombres de archivo, títulos y Open Graph',
                '⌨️ <strong>Teclado, 404 y formularios (5 preguntas):</strong> saltar, aria-current, rutas, Netlify y contraste',
                '🧩 <strong>Figma (2 preguntas):</strong> exportar el icono y compartir el enlace'],
    pre=[
        q('Sesión 14', 'Utilidades', '¿Qué hace la utilidad `mb-3` de Bootstrap?',
          ['Pone un margen inferior de 1rem (16px)', 'Pone un relleno de 3px', 'Hace el texto tres veces más grande', 'Oculta el elemento en el celular'], 0,
          '`m` es margin, `b` es bottom y `3` es 1rem. Los tamaños van de 0 a 5.'),
        q('Sesión 14', 'Utilidades', '¿Qué significa `p-4 p-md-5` en el llamado de la página Cursos?',
          ['48px en el celular y 24px desde 768px', '24px de relleno en el celular y 48px desde 768px', 'Siempre 24px', 'Margen de 4 y 5 píxeles'], 1,
          'Una utilidad con punto de quiebre vale desde ese ancho hacia arriba, como la grilla.'),
        q('Sesión 14', 'card', 'En el componente `card`, ¿qué es `card-footer`?',
          ['El título de la tarjeta', 'La imagen de la tarjeta', 'El pie de la tarjeta, con una línea encima', 'Un botón que cierra la tarjeta'], 2,
          'En la página Cursos, el pie lleva la duración y el botón «Inscribirme».'),
        q('Sesión 14', 'Accesibilidad', '¿Para qué sirve la clase `visually-hidden`?',
          ['Para borrar el elemento del HTML', 'Para mostrarlo solo en el celular', 'Para hacerlo transparente al pasar el cursor', 'Para ocultar un texto a la vista, pero que el lector de pantalla lo lea'], 3,
          'Completa los seis botones «Inscribirme»: «Inscribirme en Diseño Web».'),
        q('Sesión 14', 'Modal', '¿Qué hace un botón con `data-bs-toggle="modal"` y `data-bs-target="#inscripcion"`?',
          ['Abre la ventana modal cuyo `id` es `inscripcion`', 'Envía el formulario', 'Cambia el color del botón', 'Abre una pestaña nueva'], 0,
          'El `#` indica un `id`, como en un selector de CSS.'),
        q('Sesión 14', 'JavaScript', '¿Dónde se enlaza `bootstrap.bundle.min.js`?',
          ['En el `<head>`, antes de Bootstrap', 'Al final del `<body>`, cuando el HTML ya existe', 'Dentro de `cursos.css`', 'En cada botón'], 1,
          'Así el JavaScript encuentra los botones, el acordeón y la ventana que ya cargaron.'),
        q('Sesión 14', 'Tema', '¿En qué orden se enlazan las hojas en `cursos.html`?',
          ['`global.css`, Bootstrap y el tema', 'El tema, `global.css` y Bootstrap', 'Bootstrap, `tema-bootstrap.css` y después tus hojas', 'El orden no importa'], 2,
          'El tema va justo después de Bootstrap para cambiar sus variables; tus hojas, al final.'),
        q('Sesión 14', 'Tema', '¿Por qué el tema también define `--bs-primary-rgb`?',
          ['Porque el validador lo exige', 'Porque los colores con nombre no funcionan', 'Porque así el botón cambia en el hover', 'Porque las utilidades le añaden opacidad: `rgba(var(--bs-primary-rgb), 0.5)`'], 3,
          'Si cambias `--bs-primary`, cambia también su versión en números.'),
        q('Figma', 'Variables', 'En Relleno, ¿cómo cambias el código `06B6C4` por la variable `color-primary`?',
          ['Con el icono de cuatro puntos, Aplicar estilos y variables', 'Escribiendo el nombre de la variable en el código', 'Desde la pestaña Prototipo', 'Desde la sección Exportar'], 0,
          'Aparece al pasar el cursor sobre la fila del color.'),
        q('Figma', 'Variables', 'Cambias el valor de `color-primary` en la ventana de variables. ¿Qué pasa?',
          ['Solo cambia la capa seleccionada', 'Cambian a la vez todas las capas que usan esa variable', 'Nada, hasta reiniciar Figma', 'Se borra la variable'], 1,
          'Es lo mismo que cambiar `--color-primary` en `global.css`.'),
    ],
    post=[
        q('Sesión 15', 'Netlify', 'En tu computadora la foto se ve, pero en Netlify aparece rota. El archivo es `Foto-Carnet.jpg` y el HTML dice `foto-carnet.jpg`. ¿Por qué?',
          ['Netlify no admite imágenes JPG', 'Falta el atributo `alt`', 'El servidor de Netlify distingue mayúsculas de minúsculas', 'La imagen pesa demasiado'], 2,
          'La regla del curso: nombres en minúsculas, con guiones, sin espacios ni tildes.'),
        q('Sesión 15', '<head>', '¿Por qué cada página lleva un `<title>` distinto?',
          ['Porque el validador no acepta títulos iguales', 'Para que cargue más rápido', 'Para cambiar el color de la pestaña', 'Para distinguir las pestañas y para que Google muestre un enlace claro'], 3,
          'Primero lo propio de la página y después el nombre: «Sobre mí · Dagner Chuman».'),
        q('Sesión 15', 'Open Graph', '¿Por qué `og:image` lleva la dirección completa, con `https://`?',
          ['Porque la aplicación que arma la vista previa no está en tu sitio y no entiende una ruta relativa', 'Porque las imágenes PNG lo exigen', 'Para que el favicon se vea', 'Porque Netlify cambia los nombres de las imágenes'], 0,
          'WhatsApp o LinkedIn descargan la imagen desde su propio servidor.'),
        q('Sesión 15', 'Teclado', '¿Cómo queda escondido el enlace «Saltar al contenido» hasta el primer `Tab`?',
          ['Con `display: none`', 'Con `position: absolute` y `top: -100px`; con `:focus` baja a `top: 16px`', 'Con color blanco sobre blanco', 'Con `opacity: 0` siempre'], 1,
          'Con `display: none` no podría recibir el foco: el teclado nunca llegaría a él.'),
        q('Sesión 15', 'aria-current', '¿Qué hace `aria-current="page"` en un enlace del menú?',
          ['Abre la página en una pestaña nueva', 'Desactiva el enlace', 'Marca la página en la que estás: el lector de pantalla lo anuncia y el CSS lo puede mostrar', 'Lo resalta en Google'], 2,
          'En `header.css` usa el mismo subrayado del hover.'),
        q('Sesión 15', '404', '¿Por qué las rutas de `404.html` empiezan con `/`, como `/assets/css/global.css`?',
          ['Porque así carga más rápido', 'Porque el validador lo pide', 'Porque es una página secreta', 'Porque la 404 puede aparecer en cualquier carpeta, y `/` empieza siempre desde la raíz del sitio'], 3,
          'Desde `/proyectos/viejo.html`, una ruta `assets/…` buscaría una carpeta que no existe.'),
        q('Sesión 15', 'Netlify Forms', '¿Qué necesita un formulario para que Netlify guarde sus mensajes?',
          ['`name`, `method="post"` y `data-netlify="true"` en el `<form>`, y un `name` en cada campo', 'Un archivo JavaScript propio', 'Una base de datos', 'Solo el atributo `required`'], 0,
          'Y que la detección de formularios esté activa en el panel de Netlify antes de publicar.'),
        q('Sesión 15', 'Contraste', 'Lighthouse marca el texto blanco sobre el cian `06B6C4`: 2.47 a 1. ¿Cuánto pide la norma WCAG para el texto normal?',
          ['2 a 1', '4.5 a 1', '10 a 1', '1 a 1'], 1,
          'Para el texto grande basta 3 a 1. En el curso manda el manual; en tu proyecto, elige un color que pase.'),
        q('Figma', 'Exportar', '¿Cómo exportas el marco `favicon` de 512 × 512 como `favicon-32.png`?',
          ['Con Presentar', 'Reduciendo el marco a 32 × 32', 'En Exportar: tamaño `32w`, sufijo `-32` y formato PNG', 'Con una captura de pantalla'], 2,
          'El marco sigue en 512: Figma lo reduce al exportar.'),
        q('Figma', 'Compartir', '¿Cómo compartes tu Figma para la entrega sin que nadie lo pueda cambiar?',
          ['Enviando una captura', 'Con **puede editar**', 'Descargando el archivo .fig', 'Compartir › Cualquier persona con el enlace › **puede ver** › Copiar enlace'], 3,
          'Con **puede editar**, cualquiera con el enlace podría mover tus capas.'),
    ],
)

S16 = dict(
    n='16', tema='Simulacro del examen final (sesiones 1 a 16)',
    pre_p='Parte 1 del simulacro: HTML5, de la sesión 01 a la 07. Repasa antes del examen final.',
    post_p='Parte 2 del simulacro: CSS3, Bootstrap y la publicación, de la sesión 09 a la 15.',
    pre_desc='Simulacro · Parte 1 (HTML5)', post_desc='Simulacro · Parte 2 (CSS3, Bootstrap y despliegue)',
    pre_badge='SIMULACRO · PARTE 1 (HTML5)', post_badge='SIMULACRO · PARTE 2 (CSS3 Y BOOTSTRAP)',
    pre_corto='Parte 1',
    extra=[
        ('<span class="card-etiqueta">Saberes Previos</span>\n              <h2>Pretest</h2>',
         '<span class="card-etiqueta">Simulacro</span>\n              <h2>Parte 1</h2>'),
        ('<span class="card-etiqueta">Evaluación de Salida</span>\n              <h2>Postest</h2>',
         '<span class="card-etiqueta">Simulacro</span>\n              <h2>Parte 2</h2>'),
        ('Iniciar Pretest (10 preguntas) →', 'Iniciar la parte 1 (10 preguntas) →'),
        ('Iniciar Postest (10 preguntas) →', 'Iniciar la parte 2 (10 preguntas) →'),
        ('<span class="pill-tipo" id="badge-tipo-test">PRETEST</span>', '<span class="pill-tipo" id="badge-tipo-test">PARTE 1</span>'),
        ('badge.textContent = esPre ? "PRETEST" : "POSTEST";', 'badge.textContent = esPre ? "PARTE 1" : "PARTE 2";'),
        ('"➡️ Ir al Postest (Sesión 16)"', '"➡️ Ir a la parte 2"'),
        ('"⬅️ Ir al Pretest (Parte 1)"', '"⬅️ Ir a la parte 1"'),
        ('          ➡️ Ir al Postest\n', '          ➡️ Ir a la parte 2\n'),
    ],
    pre_lista=['🏗️ <strong>Estructura (4 preguntas):</strong> doctype, main, nav y los títulos',
               '🔗 <strong>Enlaces, imágenes y tablas (3 preguntas):</strong> target, alt y caption',
               '📝 <strong>Formularios y multimedia (3 preguntas):</strong> label, email y video'],
    post_lista=['🎨 <strong>CSS3 (6 preguntas):</strong> especificidad, variables, caja, flex, grid y transiciones',
                '📱 <strong>Responsive y Bootstrap (3 preguntas):</strong> media queries, grilla y modal',
                '🚀 <strong>Publicación (1 pregunta):</strong> Netlify Forms'],
    pre=[
        q('Sesión 01', 'Documento', '¿Para qué sirve `<!doctype html>` en la primera línea?',
          ['Le dice al navegador que el documento es HTML5 y que lo muestre en modo estándar', 'Enlaza la hoja de estilos', 'Pone el título de la pestaña', 'Hace que la página funcione sin internet'], 0,
          'Sin él, el navegador entra en un modo antiguo y algunos estilos se ven distinto.'),
        q('Sesión 02', 'Semántica', '¿Qué etiqueta envuelve el contenido principal y único de cada página?',
          ['`<section>`', '`<main>`', '`<article>`', '`<div>`'], 1,
          'Hay un solo `<main>` por página. En la sesión 15 recibe `id="contenido"`.'),
        q('Sesión 03', 'Semántica', '¿Para qué se usa `<nav>`?',
          ['Para cualquier lista', 'Para el pie de página', 'Para agrupar los enlaces de navegación del sitio', 'Para los botones de un formulario'], 2,
          'Con `aria-label` se distingue el menú principal del menú del pie.'),
        q('Sesión 02', 'Títulos', '¿Cuántos `<h1>` conviene tener en una página?',
          ['Uno por sección', 'Ninguno', 'Tantos como títulos grandes haya', 'Uno: el título principal; los demás bajan en orden, h2, h3…'], 3,
          'Los títulos forman el índice de la página para el lector de pantalla y para Google.'),
        q('Sesión 04', 'Enlaces', '¿Cómo abres un enlace externo en una pestaña nueva de forma segura?',
          ['`target="_blank" rel="noopener"`', '`href="_blank"`', '`target="new"`', '`rel="external"` solamente'], 0,
          '`noopener` evita que la página nueva controle la tuya.'),
        q('Sesión 04', 'Imágenes', '¿Para qué sirve el atributo `alt` de una imagen?',
          ['Para darle un borde', 'Para describirla al lector de pantalla y mostrar un texto si no carga', 'Para cambiar su tamaño', 'Para que cargue más rápido'], 1,
          'Si la imagen es solo decorativa, se escribe `alt=""`.'),
        q('Sesión 05', 'Tablas', '¿Qué etiqueta le da un título a una tabla?',
          ['`<th>`', '`<thead>`', '`<caption>`', '`<title>`'], 2,
          '`<th>` es una celda de encabezado; con `scope="col"` dice que encabeza una columna.'),
        q('Sesión 06', 'Formularios', '¿Qué une `<label for="correo">` con `<input id="correo">`?',
          ['Que el campo sea obligatorio', 'Que el texto se vea en negrita', 'Que el formulario se envíe solo', 'El `for` coincide con el `id`: al hacer clic en la etiqueta se enfoca el campo y el lector de pantalla la lee'], 3,
          'Es una de las primeras cosas que revisa el validador.'),
        q('Sesión 06', 'Formularios', '¿Qué hace `<input type="email" required>`?',
          ['El navegador revisa que tenga forma de correo y no deja enviar el formulario vacío', 'Envía un correo automáticamente', 'Oculta lo que se escribe', 'Muestra un calendario'], 0,
          'En el celular, además, aparece un teclado con la @.'),
        q('Sesión 07', 'Video', '¿Qué atributo necesita `<video autoplay>` para que el navegador lo reproduzca solo?',
          ['`loop`', '`muted`', '`poster`', '`preload`'], 1,
          'Los navegadores solo reproducen solos los videos sin sonido. `controls` muestra los botones.'),
    ],
    post=[
        q('Sesión 09', 'Especificidad', 'Dos reglas dan color al mismo enlace: `#menu a` y `.nav a`. ¿Cuál gana?',
          ['La que está escrita al final', 'La que tiene el color más oscuro', '`#menu a`, porque un id pesa más que una clase', '`.nav a`, porque las clases ganan siempre'], 2,
          'Solo cuando la especificidad es igual gana la que está escrita después.'),
        q('Sesión 09', 'Variables', '¿Qué hace `color: var(--color-primary);`?',
          ['Crea una variable nueva', 'Elige un color al azar', 'Pone el texto en negrita', 'Usa el valor de la variable `--color-primary` definida en `:root`'], 3,
          'Si cambias la variable, cambian todos los lugares que la usan.'),
        q('Sesión 10', 'Caja', '¿Qué cambia `box-sizing: border-box`?',
          ['El `width` incluye el relleno y el borde', 'Quita los bordes', 'Centra la caja', 'Suma el margen al ancho'], 0,
          'Por eso va en el reset de `global.css`: así las medidas coinciden con las de Figma.'),
        q('Sesión 10', 'Flexbox', 'En una fila flex, ¿qué hace `justify-content: space-between`?',
          ['Junta todo al centro', 'Pone el primer elemento al inicio, el último al final y reparte el espacio entre ellos', 'Apila los elementos', 'Agranda los elementos'], 1,
          'Es el Espacio Auto de la Disposición automática de Figma.'),
        q('Sesión 10', 'Grid', '¿Qué hace `grid-template-columns: repeat(3, 1fr)`?',
          ['Tres filas de 1px', 'Una columna de 3fr', 'Tres columnas del mismo ancho', 'Tres columnas de 1px'], 2,
          '`fr` es una fracción del espacio libre.'),
        q('Sesión 11', 'Transiciones', '¿Qué hace `transition: background-color 0.2s ease;` en un botón?',
          ['Cambia el color cada 0.2 segundos', 'Retrasa la carga de la página', 'Hace girar el botón', 'Anima el cambio de color de fondo en 0.2 segundos, por ejemplo en el hover'], 3,
          'La transición necesita un cambio de estado, como `:hover`.'),
        q('Sesión 12', 'Responsive', '¿Cuándo se aplica `@media (max-width: 600px) { … }`?',
          ['Cuando la ventana mide 600 px o menos', 'Cuando mide más de 600 px', 'Solo al imprimir', 'Siempre'], 0,
          '`max-width` es «hasta ese ancho»; `min-width`, «desde ese ancho».'),
        q('Sesión 13', 'Grilla', 'Una tarjeta tiene `col-12 col-md-6 col-lg-4`. ¿Cuántas caben por fila en el escritorio?',
          ['Una', 'Tres: cada una ocupa 4 de las 12 columnas', 'Dos', 'Doce'], 1,
          'Una por fila en el celular, dos desde 768 px y tres desde 992 px.'),
        q('Sesión 14', 'Componentes', 'El botón de la tarjeta no abre la ventana de inscripción. ¿Qué revisas primero?',
          ['El tamaño del botón', 'El color del tema', 'Que el JavaScript de Bootstrap esté enlazado y que `data-bs-target` coincida con el `id`, con `#`', 'Que la tarjeta tenga `h-100`'], 2,
          'Los componentes interactivos necesitan `bootstrap.bundle.min.js`.'),
        q('Sesión 15', 'Netlify Forms', '¿Qué atributo del `<form>` hace que Netlify detecte el formulario al publicar?',
          ['`required`', '`action="mail"`', '`method="get"`', '`data-netlify="true"`'], 3,
          'Además, `name` en el formulario y en cada campo, y `method="post"`.'),
    ],
)

if __name__ == '__main__':
    generar(S15, os.path.join(REPO, 'SESION 15', 'cuestionario-sesion15.html'))
    os.makedirs(os.path.join(REPO, 'SESION 16'), exist_ok=True)
    generar(S16, os.path.join(REPO, 'SESION 16', 'cuestionario-sesion16.html'))
