# -*- coding: utf-8 -*-
"""Cuestionarios de las sesiones 11 y 12, con el mismo generador de las sesiones 09 y 10.
uso: python3 quiz_1112.py <repo>
"""
import os
from quiz import q, generar, REPO

S11 = dict(
    n='11', tema='Transiciones, transformaciones y animaciones CSS3',
    pre_p='Mide lo que recuerdan de la sesión 10 (maquetación) antes de darle movimiento al portafolio.',
    post_p='Mide lo que aprendieron hoy: estados, transition, transform, @keyframes y el prototipo de Figma.',
    pre_desc='Saberes previos (Sesión 10: maquetación)', post_desc='Evaluación de salida (Sesión 11 y Figma)',
    pre_badge='RESULTADOS PRETEST (SESIÓN 10)', post_badge='RESULTADOS POSTEST (SESIÓN 11 Y FIGMA)',
    pre_corto='Sesión 10',
    pre_lista=['📦 <strong>Modelo de caja:</strong> padding, margin y display',
               '↔️ <strong>Flexbox:</strong> ejes, gap, flex y flex-wrap',
               '▦ <strong>Grid:</strong> fr y grid-column',
               '🧩 <strong>Figma:</strong> el Flujo de la Disposición automática'],
    post_lista=['🖱️ <strong>Estados (1 pregunta):</strong> :hover',
                '⏱️ <strong>Transiciones (3 preguntas):</strong> dónde va, duración y qué se anima',
                '🔄 <strong>Transformaciones y animaciones (3 preguntas):</strong> transform, @keyframes y movimiento reducido',
                '🧩 <strong>Figma (3 preguntas):</strong> instancia, Mientras se pasa el cursor y Animación inteligente'],
    pre=[
        q('Sesión 10', 'Modelo de caja', '¿Qué propiedad de CSS corresponde al **Espaciado** de un marco de Figma?',
          ['`margin`', '`gap`', '`padding`', '`border`'], 2,
          'El Espaciado es el relleno interno, entre el borde del marco y su contenido: `padding`. La separación entre hijos (Espacio) es `gap`.'),
        q('Sesión 10', 'Flexbox', 'En `header { display: flex; align-items: center; }`, ¿en qué dirección centra `align-items`?',
          ['En horizontal', 'En vertical', 'En las dos', 'En ninguna: falta `justify-content`'], 1,
          'Con `flex-direction: row` (por defecto), el eje cruzado es el vertical. `align-items` trabaja en el cruzado.'),
        q('Sesión 10', 'Flexbox', '¿Qué propiedad separa a los hijos de un contenedor flex, como el **Espacio** de Figma?',
          ['`gap`', '`spacing`', '`padding`', '`margin-between`'], 0,
          '`gap` pone la misma separación entre todos los hijos, sin margen extra en los extremos.'),
        q('Sesión 10', 'flex', '¿Qué significa `flex: 0 0 480px` en un ítem flex?',
          ['Que crece hasta 480 px', 'Que no crece, no se encoge y mide 480: el Ancho fijo de Figma', 'Que mide 480 px de alto', 'Que se oculta por debajo de 480 px'], 1,
          'Los tres valores son crecer, encoger y base. Con 0 y 0 el ítem mide exactamente 480, como `about-graphic` en Figma.'),
        q('Sesión 10', 'Grid', '¿Qué hace `grid-column: 1 / -1;` en los botones del formulario?',
          ['Los oculta', 'Los pone en la primera columna', 'Les quita el borde', 'Los estira desde la primera hasta la última línea: ocupan todas las columnas'], 3,
          'Las líneas de la rejilla se numeran desde 1 y la última también se llama -1.'),
        q('Sesión 10', 'Centrado', '¿Qué hace `margin: 0 auto;` en una caja con `max-width: 1440px`?',
          ['La centra en horizontal repartiendo el espacio que sobra', 'Le quita todo el margen', 'La centra en vertical', 'La pega a la izquierda'], 0,
          '`auto` reparte a los lados el espacio sobrante. Así se centra `main` en pantallas más anchas que 1440.'),
        q('Sesión 10', 'display', '¿Cuál de estas etiquetas es **inline** por defecto?',
          ['`<div>`', '`<section>`', '`<a>`', '`<p>`'], 2,
          'Los enlaces, `span`, `img` y `strong` van dentro de la línea de texto. `div`, `section` y `p` son `block`.'),
        q('Sesión 10', 'Grid', '¿Qué resultado da `grid-template-columns: 315px 1fr;`?',
          ['Dos columnas iguales', 'Una columna fija de 315 px y otra con todo el espacio que sobra', 'Una columna de 316 px', 'Dos filas'], 1,
          'Una medida fija se puede mezclar con `fr`. Es la rejilla de la multimedia: el video vertical y el resto.'),
        q('Sesión 10', 'Flexbox', '¿Qué hace `flex-wrap: wrap` en el menú del pie de página?',
          ['Envuelve los enlaces en un borde', 'Los ordena al revés', 'Los centra', 'Si no caben, los enlaces bajan a otra línea'], 3,
          'Sin `wrap`, los ítems se aprietan en una sola fila aunque no quepan. Es útil en el celular.'),
        q('Figma', 'Disposición automática', 'Un marco de Figma tiene Flujo **vertical** (flecha ↓). ¿Qué se escribe en CSS?',
          ['`flex-direction: row;`', '`flex-direction: column;`', '`display: block;`', '`align-items: column;`'], 1,
          'Flujo → es `row` (el valor por defecto) y Flujo ↓ es `column`, siempre con `display: flex` en el contenedor.'),
    ],
    post=[
        q('Sesión 11', 'Estados', '¿Qué pseudo-clase se aplica mientras el cursor está encima de un elemento?',
          ['`:active`', '`:focus`', '`:hover`', '`:visited`'], 2,
          '`:hover` dura mientras el cursor está encima. `:active`, mientras se presiona; `:focus`, mientras el elemento tiene el foco.'),
        q('Sesión 11', 'transition', 'Para que el cambio sea suave al entrar **y al salir** el cursor, ¿dónde se escribe `transition`?',
          ['En la regla `:hover`', 'En la regla normal del elemento', 'Dentro de `@keyframes`', 'En el HTML'], 1,
          'Si va en `:hover`, solo existe mientras el cursor está encima: al salir, el cambio es de golpe.'),
        q('Sesión 11', 'transition', 'En `transition: transform 0.2s ease-out;`, ¿qué indica `0.2s`?',
          ['El retraso', 'La curva', 'Las repeticiones', 'La duración'], 3,
          'El orden es propiedad, duración, curva y retraso (opcional). `0.2s` son 200 ms, la duración de la Animación inteligente de Figma.'),
        q('Sesión 11', 'Qué se anima', '¿Cuál de estas propiedades **no** se puede animar con `transition`?',
          ['`opacity`', '`background-color`', '`transform`', '`display`'], 3,
          'Solo se animan valores con intermedios. Entre `none` y `block` no hay mitad: cambia de golpe.'),
        q('Sesión 11', 'transform', 'Quieres que un botón suba 2 px al pasar el cursor **sin mover a sus vecinos**. ¿Qué escribes?',
          ['`transform: translateY(-2px);`', '`margin-top: -2px;`', '`padding-bottom: 2px;`', '`top: -2px;`'], 0,
          '`transform` mueve el elemento después de colocarlo: los demás no se enteran. `margin` y `padding` empujan.'),
        q('Sesión 11', '@keyframes', '¿Qué diferencia una animación con `@keyframes` de una transición?',
          ['No hay diferencia', 'La transición solo cambia colores', 'La animación arranca sola y puede repetirse; la transición necesita un cambio de estado', 'La animación solo funciona en Figma'], 2,
          'Por eso la entrada del Hero es una animación: ocurre al cargar la página, sin que nadie pase el cursor.'),
        q('Sesión 11', 'Movimiento reducido', '¿Para qué sirve `@media (prefers-reduced-motion: reduce)`?',
          ['Para que la página cargue más rápido', 'Para quitar las animaciones a quien pidió menos movimiento en su sistema', 'Para los celulares', 'Para imprimir la página'], 1,
          'Algunas personas se marean con las animaciones y lo indican en su sistema operativo. La página debe respetarlo.'),
        q('Figma', 'Componentes', 'En Figma, ¿qué es una **instancia**?',
          ['Una copia conectada al componente principal', 'Una variante del botón', 'Un marco con Disposición automática', 'Una interacción del prototipo'], 0,
          'Si cambias el componente principal, cambian todas sus instancias. En Capas, la instancia tiene el icono de un rombo vacío.'),
        q('Figma', 'Prototipo', 'El desencadenante **Mientras se pasa el cursor (While hovering)** equivale en CSS a…',
          ['`:active`', '`:focus`', '`@keyframes`', '`:hover`'], 3,
          'Igual que `:hover`, vuelve sola al estado normal cuando el cursor se va: no hace falta una segunda interacción.'),
        q('Figma', 'Prototipo', 'Una interacción con **Animación inteligente**, **Salida suave** y **200 ms** se escribe en CSS como…',
          ['`animation: 200 smart;`', '`transform: ease-out;`', '`transition: background-color 0.2s ease-out;`', '`@keyframes 200ms`'], 2,
          'La Animación inteligente es una `transition`: la propiedad que cambia, la duración y la curva.'),
    ],
)

S12 = dict(
    n='12', tema='Diseño web responsivo y Taller TA2',
    pre_p='Mide lo que recuerdan de la sesión 11 (transiciones y animaciones) antes de adaptar el portafolio al celular.',
    post_p='Mide lo que aprendieron hoy: viewport, media queries, medidas fluidas y la versión móvil en Figma.',
    pre_desc='Saberes previos (Sesión 11: animaciones)', post_desc='Evaluación de salida (Sesión 12 y Figma)',
    pre_badge='RESULTADOS PRETEST (SESIÓN 11)', post_badge='RESULTADOS POSTEST (SESIÓN 12 Y FIGMA)',
    pre_corto='Sesión 11',
    pre_lista=['🖱️ <strong>Estados:</strong> :hover y :active',
               '⏱️ <strong>Transiciones:</strong> duración y curva',
               '🔄 <strong>Transformaciones:</strong> scale, transform-origin y selectores con :hover',
               '🎞️ <strong>Animaciones:</strong> @keyframes, both y steps',
               '🧩 <strong>Figma:</strong> variantes'],
    post_lista=['📱 <strong>Viewport y media queries (4 preguntas):</strong> viewport, max-width, orden y min-width',
                '🌊 <strong>Medidas fluidas (3 preguntas):</strong> clamp(), auto-fit y aspect-ratio',
                '🧩 <strong>Figma móvil (3 preguntas):</strong> ancho del marco, Flujo y Llenar el contenedor'],
    pre=[
        q('Sesión 11', 'Estados', '`.btn:active` y `.btn-primary:hover` tienen la misma especificidad. Al presionar el botón, ¿cuál gana?',
          ['La que está escrita después', '`:hover`, siempre', '`:active`, siempre', 'Ninguna: se anulan'], 0,
          'Con la misma especificidad gana el orden. Por eso `.btn:active` va después de los `:hover`.'),
        q('Sesión 11', 'Curvas', '¿Qué curva conviene para responder al cursor?',
          ['`linear`', '`ease-in`', '`ease-out`', '`steps(1)`'], 2,
          '`ease-out` arranca rápido y frena al llegar: la respuesta se siente inmediata. Es la Salida suave de Figma.'),
        q('Sesión 11', 'Duración', '¿Cuánto debe durar la transición de un botón?',
          ['Unos 2 segundos', 'Entre 150 y 400 ms', 'Menos de 10 ms', 'Un minuto'], 1,
          'Menos de 100 ms no se percibe y más de 500 ms hace lenta la página. Los botones usan `0.2s`.'),
        q('Sesión 11', 'transform', '¿Qué hace `transform: scale(1.05);` en la imagen de una tarjeta?',
          ['La mueve 5 px', 'La gira 5 grados', 'La achica un 5 %', 'La agranda un 5 %'], 3,
          '`1` es el tamaño normal. `overflow: hidden` en la tarjeta recorta lo que sobra.'),
        q('Sesión 11', 'animation', '¿Qué hace `both` en `animation: aparecer 0.8s ease-out 0.2s both;`?',
          ['Repite la animación dos veces', 'Muestra el primer fotograma mientras espera y se queda en el último al terminar', 'Anima hacia adelante y hacia atrás', 'Aplica la animación a dos elementos'], 1,
          'Sin `both`, la columna se vería quieta durante el retraso y después saltaría a `opacity: 0` para empezar.'),
        q('Sesión 11', '@keyframes', 'En un `@keyframes`, ¿qué son `from` y `to`?',
          ['El 0 % y el 100 % de la animación', 'El primer y el último elemento', 'Dos animaciones distintas', 'El retraso y la duración'], 0,
          'Entre los dos puedes poner los porcentajes que quieras, como el `50%` de `parpadeo`.'),
        q('Sesión 11', 'Selectores', '¿Qué selecciona `.project-card:hover .project-image`?',
          ['Todas las imágenes de la página', 'La tarjeta, solo si la imagen tiene el cursor encima', 'La imagen dentro de una tarjeta que tiene el cursor encima', 'La imagen, solo si se presiona'], 2,
          'El `:hover` está en la tarjeta y el espacio indica un descendiente: basta con poner el cursor sobre el texto de la tarjeta.'),
        q('Sesión 11', 'Curvas', '¿Qué hace `steps(1)` en la animación del cursor que parpadea?',
          ['La hace más lenta', 'La repite una vez', 'La hace girar', 'Cambia de golpe, sin valores intermedios'], 3,
          'El cursor se enciende y se apaga como en un editor de código, sin pasar por medias opacidades.'),
        q('Sesión 11', 'transform', 'Si no escribes `transform-origin`, ¿desde dónde gira o se escala un elemento?',
          ['Desde la esquina superior izquierda', 'Desde su centro', 'Desde la esquina inferior derecha', 'Desde el centro de la página'], 1,
          'El valor por defecto es el centro. Por eso el círculo de contacto gira sobre sí mismo.'),
        q('Figma', 'Variantes', 'En Figma, ¿dónde viven las variantes `Estado=Predeterminado` y `Estado=Hover`?',
          ['En la pestaña Prototipo', 'En un estilo de color', 'Dentro de `mi-portafolio`', 'En un conjunto de componentes, un marco con borde morado discontinuo'], 3,
          'El conjunto se guarda fuera de la página, en el lienzo. En la página va una instancia del componente.'),
    ],
    post=[
        q('Sesión 12', 'viewport', '¿Qué pasa en un celular si falta `<meta name="viewport" content="width=device-width, initial-scale=1.0">`?',
          ['No carga el CSS', 'Funciona igual', 'Muestra la página en miniatura, como si la pantalla midiera unos 980 px', 'La página queda en blanco'], 2,
          'Sin esa línea, el celular finge una pantalla ancha y ninguna media query de 600 px se activa.'),
        q('Sesión 12', 'Media queries', '¿Cuándo se aplican las reglas de `@media (max-width: 600px) { … }`?',
          ['Cuando la ventana mide 600 px o menos', 'Cuando la ventana mide más de 600 px', 'Solo cuando mide exactamente 600 px', 'Solo al imprimir'], 0,
          '`max-width` es «hasta ese ancho». `min-width` sería «desde ese ancho».'),
        q('Sesión 12', 'Orden', 'Escribiste la media query **antes** de la regla que corrige y en el celular no cambia nada. ¿Por qué?',
          ['Las media queries solo funcionan en archivos aparte', 'Con la misma especificidad gana la regla escrita después', 'Falta `!important`', 'Falta la etiqueta viewport'], 1,
          'Una media query no suma especificidad. Por eso las media queries van al final de cada hoja.'),
        q('Sesión 12', 'Enfoques', 'En el enfoque **celular primero** (mobile first), las media queries usan…',
          ['`max-width`', '`orientation`', '`print`', '`min-width`'], 3,
          'La regla normal es la del celular y `min-width` añade columnas al crecer. Tu portafolio usa escritorio primero, con `max-width`.'),
        q('Sesión 12', 'clamp()', 'Con `font-size: clamp(2.5rem, 1.5rem + 4vw, 4rem);`, ¿cuánto mide el título en una ventana de 390 px?',
          ['39.6 px', '64 px', '40 px', '16 px'], 2,
          '24 + 15.6 = 39.6 px queda por debajo del mínimo (2.5rem = 40 px), así que se usa el mínimo.'),
        q('Sesión 12', 'auto-fit', '¿Qué hace `grid-template-columns: repeat(auto-fit, minmax(min(100%, 360px), 1fr));`?',
          ['Pone tantas columnas de al menos 360 px como quepan y las estira', 'Pone siempre 360 columnas', 'Pone una sola columna de 360 px', 'Solo funciona dentro de una media query'], 0,
          'Dos columnas en escritorio y tablet, una en el celular, sin media query. `min(100%, 360px)` evita el desborde en pantallas angostas.'),
        q('Sesión 12', 'aspect-ratio', '¿Para qué sirve `aspect-ratio: 16 / 9;` en el iframe de YouTube?',
          ['Para que el video se reproduzca solo', 'Para que el alto se calcule a partir del ancho y conserve la proporción', 'Para que mida 16 px de ancho', 'Para quitarle el borde'], 1,
          'Una imagen conserva su proporción con `height: auto`; un iframe no. `aspect-ratio` se la da.'),
        q('Figma', 'Marco móvil', '¿Qué ancho tiene el marco `mi-portafolio-movil` de la guía de Figma?',
          ['1440', '992', '600', '390'], 3,
          '390 es el ancho de un iPhone 13 o 14, un ancho de celular muy común. Es también el ancho de prueba en DevTools.'),
        q('Figma', 'Flujo', 'En el marco móvil, `about-content` pasa de Flujo horizontal (→) a vertical (↓). En CSS, dentro de la media query…',
          ['`.about-content { flex-direction: column; }`', '`.about-content { display: none; }`', '`.about-content { flex-wrap: nowrap; }`', '`.about-content { width: 390px; }`'], 0,
          'Cada cambio de Flujo del marco móvil es un cambio de `flex-direction` en `@media`.'),
        q('Figma', 'Llenar el contenedor', '`contact-list` tenía **Ancho fijo** 520 y en el móvil pasa a **Llenar el contenedor**. ¿Qué regla lo logra en tu CSS?',
          ['`width: 520px;`', '`flex-basis: auto;` con el contenedor en columna y `align-items: stretch;`', '`overflow: hidden;`', '`flex: 0 0 520px;`'], 1,
          'En escritorio, `flex: 0 0 520px` es el Ancho fijo. En la media query, `flex-basis: auto` lo suelta y `stretch` lo estira a todo el ancho.'),
    ],
)

if __name__ == '__main__':
    generar(S11, os.path.join(REPO, 'SESION 11', 'cuestionario-sesion11.html'))
    generar(S12, os.path.join(REPO, 'SESION 12', 'cuestionario-sesion12.html'))
